### ISSUE TITLE
Add `nextEpoch` field to `ApiNetworkInformation`

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1088]
# Context

In order to support the ability for users to query the API about the _next epoch_, we need to extend the existing `getNetworkInformation` endpoint so that it provides this information.

# Decision

Add a `nextEpoch` field to the existing `ApiNetworkInformation` type, so that the definition becomes:

```hs
data ApiNetworkInformation = ApiNetworkInformation
    { networkTip :: !ApiNetworkTip
    , nextEpoch :: !ApiEpochInfo
    , nodeTip :: !ApiBlockReference   
    , syncProgress :: !(ApiT SyncProgress)
    } deriving (Eq, Generic, Show)
```
The associated swagger definition should also be updated so that the definition becomes:
```yaml
ApiNetworkInformation: &ApiNetworkInformation
  type: object
  required: 
    - sync_progress
    - node_tip
    - network_tip
    - next_epoch
  properties: 
    sync_progress: *networkInformationSyncProgress
    node_tip: *networkInformationNodeTip
    network_tip: *networkInformationNetworkTip
    next_epoch: *networkInformationNextEpoch
```

# Acceptance Criteria

- [x] The `ApiNetworkInformation` value returned by the `getNetworkInformation` endpoint _must_ contain a `nextEpoch` field of type `ApiEpochInfo`.
 
# Development 

- [x] Add wrapper function `calculateNextEpoch` around `Primitive.Types.epochCeiling` that computes the next epoch after the _current time_, based on the current `SlotParameters`.
- [x] Extend the `ApiNetworkInformation` type to include the `nextEpoch` field.
- [x] Extend function `network` in `Api.Server` to call the `calculateNextEpoch` wrapper function.

# QA 

- [x] Adjust integration tests to check that the `getNetworkInformation` endpoint returns the correct information within the `nextEpoch` field.

# PRs

| Number | Base |
| -- | -- |
| #1122 | `master` |
