### ISSUE TITLE
Create `ApiSelectCoinsData` data type.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1133]
# Context

In order to support users that wish to use a hardware wallet, we would like to expose our coin selection functionality as a new API function `selectCoins`. This function will take a list of payments as its input, and produce a coin selection as its output.

# Decision

Provide the following API datatype, values of which will be used as input to `selectCoins`:

```hs
newtype ApiSelectCoinsData (n :: NetworkDiscriminant) = ApiSelectCoinsData
    { payments :: NonEmpty (AddressAmount n)
    } deriving (Eq, Generic, Show)
```

The above type should correspond to the following Swagger definition:
```yaml
  ApiSelectCoinsData: &ApiSelectCoinsData
    type: object
    required: 
      - payments
    properties: 
      payments: *transactionOutputs
```

# Acceptance Criteria

- [x] There _must_ be an API type `ApiSelectCoinsData` that meets the definition provided above.
- [x] There _must_ be roundtrip and golden JSON serialization tests for the above type.

---

# Development 

- [x] Create the `ApiSelectCoinsData` type.
- [x] Create the corresponding Swagger definition.

# QA 

- [x] Create roundtrip and golden JSON serialization tests.

# PRs

| Number | Base |
| -- | -- |
| #1152 | `master` |
