### ISSUE TITLE
Create `ApiCoinSelection` data type.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#1134]
# Context

In order to support users that wish to use a hardware wallet, we would like to expose our coin selection functionality as a new API function `selectCoins`. This function will take a list of payments as its input, and produce a coin selection as its output.

# Decision

Provide the following API datatypes: (Values of `ApiCoinSelection` will be provided as output from `selectCoins`.)

```hs
data ApiCoinSelection (n :: NetworkDiscriminant) = ApiCoinSelection
    { inputs :: !(NonEmpty (ApiCoinSelectionInput n))
    , outputs :: !(NonEmpty (AddressAmount n))
    } deriving (Eq, Generic, Show)

data ApiCoinSelectionInput (n :: NetworkDiscriminant) = ApiCoinSelectionInput
    { id :: !(ApiT (Hash "Tx"))
    , index :: !(ApiT Word32)
    , address :: !(ApiT Address, Proxy n)
    , amount :: !(Quantity "lovelace" Natural)
    } deriving (Eq, Generic, Show)
```

The above types should correspond to the following Swagger definitions:

```yaml
  ApiCoinSelection: &ApiCoinSelection
    type: object
    required: 
      - inputs
      - outputs
    properties: 
      inputs: *transactionResolvedInputs
      outputs: *transactionOutputs

x-transactionResolvedInputs: &transactionResolvedInputs
  description: A list of transaction inputs
  type: array
  minItems: 0
  items: 
    type: object
    required: 
      - id
      - index
      - address
      - amount
    properties: 
      address: *addressId
      amount: *transactionAmount
      id: *transactionId
      index: 
        type: integer
        minimum: 0
```

# Acceptance Criteria

- [x] There _must_ be an API type `ApiCoinSelection` that meets the definition provided above.
- [x] There _must_ be an API type `ApiCoinSelectionInput` that meets the definition provided above.
- [x] There _must_ be roundtrip and golden JSON serialization tests for the above types.

# Development 

- [x] Create the `ApiCoinSelection` type.
- [x] Create the `ApiCoinSelectionInput` type.
- [x] Create the corresponding Swagger definitions.

# QA 

- [x] Create roundtrip and golden JSON serialization tests.

# PRs

| Number | Base |
| -- | -- |
| #1152 | `master` |
