### ISSUE TITLE
Better report delegation status in the context of delays

### ISSUE THREAD

**Issue by paweljakubas** [cardano-foundation/cardano-wallet#1312]
# Context

U/S

As a wallet client,
I want to reliably know how my delegation changes,
So that I can better inform users about their current and next delegation settings.

A/C

The wallet engine must only report a wallet as being delegated when it actively IS (i.e. after the 2 epochs grace period upon discovering a delegation certificate).

If multiple certificates are discovered within the same epoch, the wallet must report only about the last one.

The 'WalletAPI' model must be modified to match the following swagger definition:

# Decision

We are going to have the following situations: 
1. not delegating and not joined :
```
"delegation": {
    "active": {
      "status": "not_delegating"
      }
}
``` 
2. not delegating but joined and discovered at epoch=13 (and we are at epoch = 13)
```
"delegation": {
    "active": {
      "status": "not_delegating"
      },
     "next": {
      "status": "delegating",
      "target" : "poolId1",
      "changes_at": {
        "epoch_number": 15,
        "epoch_start_time": "2020-01-22T10:18:54.246Z"
      }}
```
3. not delegating, discovered at epoch = 13, and we are at 14:
```
"delegation": {
    "active": {
      "status": "not_delegating"
      },
     "next": {
      "status": "delegating",
      "target" : "poolId1",
      "changes_at": {
        "epoch_number": 15,
        "epoch_start_time": "2020-01-22T10:18:54.246Z"
      }}
```
4. delegating and at epoch >=15:
```
"delegation": {
    "active": {
      "status": "delegating",
      "target" : "poolId1"
      }
      }}
```
5. delegating and joining at epoch = 20 and discovered at epoch=20
```
"delegation": {
    "active": {
      "status": "delegating",
      "target" : "poolId1"
      },
     "next": {
      "status": "delegating",
      "target" : "poolId2",
      "changes_at": {
        "epoch_number": 22,
        "epoch_start_time": "2020-01-23T10:18:54.246Z"
      }}
```
6. delegating, discovered at epoch = 20 and now epoch =21
```
"delegation": {
    "active": {
      "status": "delegating",
      "target" : "poolId1"
      },
     "next": {
      "status": "delegating",
      "target" : "poolId2",
      "changes_at": {
        "epoch_number": 22,
        "epoch_start_time": "2020-01-23T10:18:54.246Z"
      }}
```
7. delegating to another pool (now epoch>=22):
```
"delegation": {
    "active": {
      "status": "delegating",
      "target" : "poolId2"
      }
      }}
```
8. delegating and quitting at epoch=25 (and discovered at epoch=25):
```
"delegation": {
    "active": {
      "status": "delegating",
      "target" : "poolId2"
      },
     "next": {
      "status": "not_delegating",
      "changes_at": {
        "epoch_number": 27,
        "epoch_start_time": "2020-01-23T10:18:54.246Z"
      }}
```
9. delegating, discovered delegation cert quitting at epoch=25, now epoch=26:
```
"delegation": {
    "active": {
      "status": "delegating",
      "target" : "poolId2"
      },
     "next": {
      "status": "not_delegating",
      "changes_at": {
        "epoch_number": 27,
        "epoch_start_time": "2020-01-23T10:18:54.246Z"
      }}
```
10. not-delegating at epoch>=27:
```
"delegation": {
    "active": {
      "status": "not_delegating"
      }
}
``` 
# Acceptance Criteria

1. Follow certificates discovered and implement logic able to deliver the "state machine" flow like described in 10 points.
2. Change swagger and api to comply with : 
```
x-delegationStatus: &delegationStatus
  required: 
    - status
  properties: &delegationStatusProperties
    status: 
      type: string
      enum: 
        - not_delegating
        - delegating
    target: 
      <<: *stakePoolId
      description: A unique Stake-Pool identifier (present only if status = `delegating`)

ApiWalletDelegation: &ApiWalletDelegation
  description: Delegation settings
  type: object
  required: 
    - active
  properties: 
    active: 
      <<: *delegationStatus
      description: Currently active delegation status.
      example: 
        status: delegating
        target: 1423856bc91c49e928f6f30f4e8d665d53eb4ab6028bd0ac971809d514c92db1
    next: 
      <<: *delegationStatus
      description: Next delegation settings about to change. Only present when a status change has to reported.
      required: 
        - status
        - changes_at
      properties: 
        <<: *delegationStatusProperties
        changes_at: *ApiEpochInfo
      example: 
        status: not_delegating
        changes_at: 
          epoch_number: 14
          epoch_start_time: 2020-01-22T10:06:39.037Z
```
3. Add thorough testing    

---

# Development 

# QA 

I have updated the following suites : 
1. Api.TypesSpec
2. Jormungandr's StakePool integration tests
3. Other tests that use `delegation`.
I would focus during QA on this and also work with endpoint directly and see ApiWallet response when certifiates are discovered, epoch changes upon joining/quiting from stake pools
