### ISSUE TITLE
'listAddresses' is extremely slow / unusable for large wallets.

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#2032]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2020-08-03  |
| Platform     | All           |
| Installation | Source             |

# Steps to Reproduce

1. Restore a wallet with a large UTxO (> 10K) 
2. List addresses via the corresponding endpoint

## Expected behavior

- Clients receive a response in a reasonable amount of time.

## Actual behavior
 

- The request is timing out even after several minutes.

---

# Resolution 

1. The main issue of this handler is that it loads in memory and crawls the ENTIRE transaction history of the wallet. This is done merely to know whether addresses have been used or not. This is unnecessary for random addresses because used and unused addresses are already separated in two different Maps. For sequential wallets it's a bit more subtle but, we can mark addresses as "Used" during discovery and store this information in the database. See #2033 

2. The server currently returns the entire address space as one big chunk and only replies once all addresses are returned. We could leverage the HTTP streaming capabilities and stream addresses as they are processed by the server so that the client get a response immediately. Exploring this idea in #2052 

3. There's no way to filter out addresses at the moment, so it'd be nice to also have a way to filter addresses based on:
  a. Their state (used vs unused)
  b. Their ID 

  TODO.

4. We need to be able to catch these errors upfront before they reach exchanges' production environment. However, generating such large wallets is tricky. We already have a special "unsound wallet" we use in nightly benchmarks which recognizes addresses based on a checksum and a proportion defined upfront (like, 1% of all addresses). The downside of this special scheme is that the internal address state is very simple (only a double for the proportion) and does not exercise the wallet fully when it comes to storing and retrieving addresses. We could extend this concept to wrap the random and sequential wallets around this, so that we also get to test functionalities related to the address space too. Done in #2081 #2084

---

# QA 

- Last nightly benchmarks results (https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/636#e79c244b-d2c0-43a5-8d24-36d07f5bc7bf)

```
BenchSeqResults:
  listAddressesTime: 6.834 ms
  utxoStatistics:
    = Total value of -0 lovelace across 0 UTxOs
 
BenchRndResults:
  listAddressesTime: 385.6 μs
  utxoStatistics:
    = Total value of -0 lovelace across 0 UTxOs
 
BenchRndResults:
  listAddressesTime: 142.0 ms
  utxoStatistics:
    = Total value of 21515725326443 lovelace across 747 UTxOs
 
BenchRndResults:
  listAddressesTime: 1.164 s
  utxoStatistics:
    = Total value of 31020480179736 lovelace across 1392 UTxOs
 
BenchRndResults:
  listAddressesTime: 2.806 s
  utxoStatistics:
    = Total value of 69284306530582 lovelace across 2779 UTxOs
 
BenchSeqResults:
  listAddressesTime: 1.573 s
  utxoStatistics:
    = Total value of 21515725326443 lovelace across 747 UTxOs
 
BenchSeqResults:
  listAddressesTime: 5.423 s
  utxoStatistics:
    = Total value of 31070480179736 lovelace across 1393 UTxOs
 
BenchSeqResults:
  listAddressesTime: 4.073 s
  utxoStatistics:
    = Total value of 67838832136562 lovelace across 2780 UTxOs
```
