### ISSUE TITLE
Creating an address takes a massive amount of time on large wallets

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#2051]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  |
| Platform     |           |
| Installation |             |

# Steps to Reproduce

1. Have a large Byron wallet (100K+ transactions, 50K+ UTxO, 50K+ existing addresses).
2. Import a single address using the `/byron-wallets/addresses` endpoint

## Expected behavior

1. The address is promptly imported.

## Actual behavior
 

1. The wallet hangs for several minutes before completing the operation.

---

# Resolution 

- A possible started would be to look more closely at the strictness of the `scanl` used in the handler.

---

# QA 

- Benchmark results from last night (https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/636#e79c244b-d2c0-43a5-8d24-36d07f5bc7bf)

```
BenchRndResults:
  importOneAddressTime: 1.510 ms
  importManyAddressesTime: 187.3 ms
  utxoStatistics:
    = Total value of -0 lovelace across 0 UTxOs
 
BenchRndResults:
  importOneAddressTime: 328.9 ms
  importManyAddressesTime: 789.7 ms
  utxoStatistics:
    = Total value of 21515725326443 lovelace across 747 UTxOs
 
BenchRndResults:
  importOneAddressTime: 942.2 ms
  importManyAddressesTime: 1.886 s
  utxoStatistics:
    = Total value of 31020480179736 lovelace across 1392 UTxOs

BenchRndResults:
  importOneAddressTime: 1.770 s
  importManyAddressesTime: 3.551 s
  utxoStatistics:
    = Total value of 69284306530582 lovelace across 2779 UTxOs
```

Note: many = 1000
