### ISSUE TITLE
Property `prop_rebalanceSelection` occasionally fails.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#2118]
# Context

Instances of this failure:
 
1. https://hydra.iohk.io/build/4063979/nixlog/7
1. https://hydra.iohk.io/build/4208599/nixlog/1
1. https://hydra.iohk.io/build/4605661/nixlog/55
1. https://hydra.iohk.io/build/4865823/nixlog/3
1. https://hydra.iohk.io/build/4866583/nixlog/1

# Test Case

`prop_rebalanceSelection`

# Failure / Counter-example

```hs
      Falsifiable (after 5023 tests):
         SaveMoney
         Coin {getCoin = 105080}
         selection (before):
         inputs: - 2nd 409786d4 (~ 166350 @ 61646472...64722d33)
         withdrawal: 618680
         reclaim: -0
         outputs:
           - 74251 @ 61646472...64722d33
           - 76285 @ 61646472...64722d33
           - 163463 @ 61646472...64722d32
           - 198051 @ 61646472...64722d30
         change: [272980]
         deposit: -0

         selection (after):
         inputs: - 2nd 409786d4 (~ 166350 @ 61646472...64722d33)
         withdrawal: 618680
         reclaim: -0
         outputs:
           - 74251 @ 61646472...64722d33
           - 76285 @ 61646472...64722d33
           - 163463 @ 61646472...64722d32
           - 198051 @ 61646472...64722d30
         change: [105080]
         deposit: -0

         delta (before): 0
         delta (after):  167900
         total fee:      167900
         remaining fee:  0


  To rerun use: --match "/Cardano.Wallet.Primitive.Fee/prop_rebalanceSelection/The fee balancing algorithm converges for any coin selection./"

Randomized with seed 1973157653
```

# Resolution 

---

# QA

**Comment by jonathanknowles** [comment]
Seen again here: https://hydra.iohk.io/build/4605661/nixlog/55/tail.

Extract:

```hs
  test/unit/Cardano/Wallet/Primitive/FeeSpec.hs:379:9: 
  1) Cardano.Wallet.Primitive.Fee.prop_rebalanceSelection The fee balancing algorithm converges for any coin selection.
       Falsifiable (after 1412 tests):
         SaveMoney
         Coin {getCoin = 75091}
         selection (before):
         inputs: - 1st 1b0e0d01 (~ 191127 @ 61646472...64722d33)
         withdrawal: 661092
         reclaim: -0
         outputs:
           - 179239 @ 61646472...64722d30
           - 65871 @ 61646472...64722d31
           - 169386 @ 61646472...64722d32
           - 194332 @ 61646472...64722d31
         change: [243391]
         deposit: -0
         
         selection (after):
         inputs: - 1st 1b0e0d01 (~ 191127 @ 61646472...64722d33)
         withdrawal: 661092
         reclaim: -0
         outputs:
           - 179239 @ 61646472...64722d30
           - 65871 @ 61646472...64722d31
           - 169386 @ 61646472...64722d32
           - 194332 @ 61646472...64722d31
         change: [75091]
         deposit: -0
         
         delta (before): 0
         delta (after):  168300
         total fee:      168300
         remaining fee:  0
         

  To rerun use: --match "/Cardano.Wallet.Primitive.Fee/prop_rebalanceSelection/The fee balancing algorithm converges for any coin selection./"

Randomized with seed 826758594
```

**Comment by Anviking** [comment]
Saw locally once:
```
 test/unit/Cardano/Wallet/Primitive/FeeSpec.hs:374:9:
  1) Cardano.Wallet.Primitive.Fee.prop_rebalanceSelection The fee balancing algorithm converges for any coin selection.
       Falsifiable (after 1996 tests):
         SaveMoney
         Coin {getCoin = 151662}
         selection (before):
         inputs: - 2nd 3bfc8bf9 (~ 183483 @ 61646472...64722d31)
         withdrawal: 556018
         reclaim: -0
         outputs:
           - 47175 @ 61646472...64722d32
           - 36274 @ 61646472...64722d31
           - 192524 @ 61646472...64722d33
           - 145066 @ 61646472...64722d32
         change: [318462]
         deposit: -0

         selection (after):
         inputs: - 2nd 3bfc8bf9 (~ 183483 @ 61646472...64722d31)
         withdrawal: 556018
         reclaim: -0
         outputs:
           - 47175 @ 61646472...64722d32
           - 36274 @ 61646472...64722d31
           - 192524 @ 61646472...64722d33
           - 145066 @ 61646472...64722d32
         change: [151662]
         deposit: -0

         delta (before): 0
         delta (after):  166800
         total fee:      166800
         remaining fee:  0


  To rerun use: --match "/Cardano.Wallet.Primitive.Fee/prop_rebalanceSelection/The fee balancing algorithm converges for any coin selection./"

Randomized with seed 1566303677
```

**Comment by jonathanknowles** [comment]
Seen again here: https://github.com/input-output-hk/cardano-wallet/pull/2335#issuecomment-730285682

**Comment by hasufell** [comment]
https://buildkite.com/input-output-hk/cardano-wallet/builds/12201#551d00fe-857e-45a4-96eb-df60a02a37f5

```
    Failures:
 
      test/unit/Cardano/Wallet/Primitive/FeeSpec.hs:381:9:
      1) Cardano.Wallet.Primitive.Fee.prop_rebalanceSelection The fee balancing algorithm converges for any coin selection.
           Falsifiable (after 3044 tests):
             Coin {getCoin = 114754}
             selection (before):
             inputs: - 1st 509187c5 (~ 197140 @ 61646472...64722d32)
             withdrawal: 502225
             reclaim: 3567
             outputs:
               - 72698 @ 61646472...64722d33
               - 175789 @ 61646472...64722d32
               - 2336 @ 61646472...64722d32
               - 86104 @ 61646472...64722d33
               - 74851 @ 61646472...64722d30
             change: [287587]
             deposit: -0
 
             selection (after):
             inputs: - 1st 509187c5 (~ 197140 @ 61646472...64722d32)
             withdrawal: 502225
             reclaim: 3567
             outputs:
               - 72698 @ 61646472...64722d33
               - 175789 @ 61646472...64722d32
               - 2336 @ 61646472...64722d32
               - 86104 @ 61646472...64722d33
               - 74851 @ 61646472...64722d30
             change: [114754]
             deposit: -0
 
             delta (before): 3567
             delta (after):  176400
             total fee:      176400
             remaining fee:  0
 
      To rerun use: --match "/Cardano.Wallet.Primitive.Fee/prop_rebalanceSelection/The fee balancing algorithm converges for any coin selection./"
 
    Randomized with seed 1510629119
 
    Finished in 927.5904 seconds
    2426 examples, 1 failure, 2 pending

```
