### ISSUE TITLE
Jörmungandr block format

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#218]
# Context

Jörmungandr introduces a new binary block format. This format is described in 
[rust-cardano-/chain-impl-mockchain/doc/format.md](https://github.com/input-output-hk/rust-cardano/blob/master/chain-impl-mockchain/doc/format.md).

In order to integrate with Jörmungandr, we therefore need to build a few
primitives first, starting with the block format. As a starter for testing, 
we have the following test vector for the a genesis block generated via `jcli`:

```
005200000000009f000000000000000000000000ffadebfecd59d9eaa12e903a
d58100f7c1e35899739c3d05d022835c069d2b4f000000000000000000000000
00000000000000000000000000000000000000000047000048000000005cc1c2
4900810200c200010108000000000000087001410f01840000000a01e030a694
b80dbba2d1b8a4b55652b03d96315c8414b054fa737445ac2d2a865c76002604
0001000000ff0005000006000000000000000000000000000000000000000000
0000000000002c020001833324c37869c122689a35917df53a4f2294a3a52f68
5e05f5f8e53b87e7ea452f000000000000000e
```

> NOTE: 
>
> Convert back to raw bytes using `Data.ByteArray.Encoding(convertFromBase, Base16)`

# Decision

- Implement block decoder, in a modular fashion, similar to the existing
  implementation for the http-bridge (so this includes a transaction decoder,
  certificate decoder etc...)

- Disregard for now, anything related to transactions and only focus on the block structure and what's available in the genesis block.

# Acceptance Criteria

1. We _must_ have a type-1 (common structure) binary decoder for the new block format used by Jörmungandr
2. We _must_ have a binary decoder that also supports decoding block headers in the format used by Jörmungandr 
3. Type 2, Type 3, Type 4 and Type 5 binary decoders _may_ be left for later.

---

# Development Plan
## Setup
- [x] Create a new package
- [x] Write a unit test, with stubbed `undefined` functions
- I plan on using the `binary` package
- [x] Decode the genesis blockHeader and check/debug/log that values seem sane (e.g the decoded sizes-values are correct)

## Then
- [x] Decode `Initial` message
- [x] Decode `Transaction` message
- ?

# PR

- #244 
- #245 
- #266 
- #273 
- #275 

# QA 

We have decoders for block headers, and the `Initial [ConfigParam]` and `Transaction Tx` (slightly incomplete) messages. 

We test the decoders on one genesis block. 

I think the plan for the future is to have more blocks to test against (after #242), and make the decoders more complete.

- The decoders are fairly strict.
    - There is a lot of size information, so we can use [`isolate`](https://hackage.haskell.org/package/binary-0.8.6.0/docs/Data-Binary-Get.html#v:isolate) extensively.
    - Throws on un-recognized constants/tags

- There is some intricate logic that we don't want to get wrong, but they are/should be covered easily by more blocks as test vectors.

**Comment by Anviking** [comment]
I think the example is wrong 🙃 (or so I hope at least)

The `Initial`- and `Transaction`-messages were just way off from the format spec (and mockchain code).

This (from the mockchain) works much better:

<details>

```diff
diff --git a/chain-impl-mockchain/src/multiverse.rs b/chain-impl-mockchain/src/multiverse.rs
index ae8c69f4..719132ce 100644
--- a/chain-impl-mockchain/src/multiverse.rs
+++ b/chain-impl-mockchain/src/multiverse.rs
@@ -275,6 +275,10 @@ mod test {
     use quickcheck::{Arbitrary, StdGen};
     use std::time::SystemTime;

+    use std::io::prelude::*;
+    use std::fs::File;
+    use chain_core::property::Serialize;
+
     fn apply_block(state: &Ledger, block: &Block) -> Ledger {
         if state.chain_length().0 != 0 {
             assert_eq!(state.chain_length().0 + 1, block.chain_length().0);
@@ -328,6 +332,12 @@ mod test {
         let mut _root = None;
         let mut parent = genesis_block.id();
         let mut ids = vec![];
+
+        let mut f = File::create("foo.txt").unwrap();
+        let vs = Serialize::serialize(&genesis_block, f);
+        panic!("genesis block: {:?}", vs);
+
+
         for i in 1..10001 {
             let mut block = BlockBuilder::new();
             block.chain_length(state.chain_length.next());
```

</details>

```
00520000000000450000000000000000000000000873e3c710075f5fe45352c16ff15b16d76410687a20872fa36eff88147cf47f0000000000000000000000000000000000000000000000000000000000000000004300000600810200c2000102e03ebedfc75fc6c7ddf2342ade92d211a02d59a5e0486ea09d00d88d7a9b9ddc9e0048000000000000000001410a020800000000000001f4
```
though it is only the `Initial` message.

**Comment by KtorZ** [comment]
@Anviking So indeed, the format seems to have changed a bit but after checking with the Rust team, the documentation seems _okay_. Here-below is a new genesis block generated from the latest master branch (+ some small tweaks to resolve compile-error :s). It should also include some initial certificate and legacy funds. So, more fun to decode:

```
00520000000001ca000000000000000000000000f7becdf807c706cef54ec4832d2a747591c3f21
41de3e4f2aef59a130d890c12000000000000000000000000000000000000000000000000000000
0000000000007c00000c0088000000005cc1c24900410200c2000101040000087001410f0184000
0000a02e030a694b80dbba2d1b8a4b55652b03d96315c8414b054fa737445ac2d2a865c76020800
000000000000dc0244000000ff028800000000000000dc034101039800000000000000000000000
0000000000000000000000000002c020001833324c37869c122689a35917df53a4f2294a3a52f68
5e05f5f8e53b87e7ea452f000000000000000e00620101000000000000007b005682d818584c835
81c2ac3cc97bbec476496e84807f35df7349acfbaece200a24b7e26250ca20058208200581ca6d9
aef475f3418967e87f7e93f20f99d8c7af406cba146affdb71910146450102030405001a89a5937
100b803000004000000000000000000000000000000d501d0fa7e180d33987d17f77cbf70e1463b
ce01d32d952ed6f9823f0d69eb37e35f931417c6075e0f3e5858198fe15831ba7fb51368fa2f0ac
27a799032729e08a624a4aafb7a4dde35e4742d258d04c5f3ec87e616b9bcb0cdc070b503fe634b
46010040a856b8a6f8d18d588b5e1cfd3ea2e56ae45b80126bb25feb8ccde27fe61ebc7fd64deb7
667ab1a79ca2448f56e60f3097c2fa657febdec19e7bd7abfb0ea4705
```

**Comment by Anviking** [comment]
I am thinking of starting #242  to get more blocks to test vectors here… 🤔

**Comment by KtorZ** [comment]
By the way @Anviking, this is the genesis file that was used to generate the block above:

```yaml
# The Blockchain Configuration defines the different settings
# of the blockchain that cannot be changed once the blockchain
# is started.
blockchain_configuration:

  # The block0-date defines the date the blockchain starts
  # expected value in seconds since UNIX_EPOCH
  block0_date: 1556202057

  # This is the type of dicrimination of the blockchain
  # of this blockchain is meant for production then
  # use 'production' instead.
  #
  # otherwise leave as this
  discrimination: test

  # The initial consensus version:
  #
  # * BFT consensus: bft
  # * Genesis Praos consensus: genesis
  block0_consensus: bft

  # Number of slots in each epoch
  slots_per_epoch: 2160

  # The slot duration, in seconds, is the time between the creation
  # of 2 blocks
  slot_duration: 15

  # The number of blocks (*10) per epoch
  epoch_stability_depth: 10

  # A list of Ed25519 Extended PublicKey that represents the
  # BFT leaders encoded as bech32. The order in the list matters.
  consensus_leader_ids:
    - ed25519e_pk1xznffwqdhw3drw9yk4t99vpajcc4epq5kp205um5gkkz625xt3mqn4z3mx

  # Genesis praos parameter D
  bft_slots_ratio: 0.220

  # Genesis praos active slot coefficient
  # Determines minimum stake required to try becoming slot leader, must be in range (0,1]
  consensus_genesis_praos_active_slot_coeff: 0.22

  # This is the max number of messages allowed in a given Block
  max_number_of_transactions_per_block: 255

  # Allow the creation of accounts from the output of a transaction
  #
  # if set to false, account based wallet will not be created without
  # publishing a stake certificate.
  # if set to true, simply adding the account in the output of a transaction
  # will allow the account to exist in the blockchain.
  allow_account_creation: true

  # The fee calculations settings
  #
  # fee(num_bytes, has_certificate) = constant + num_bytes * coefficient + has_certificate * certificate
  linear_fee:
    constant: 0
    coefficient: 0
    certificate: 0

  kes_update_speed: 16

# The initial deposits present in the blockchain.
#
# It can be UTxO addresses or account (if allow_account_creation is set).
initial_funds:
  - address: ta1svejfsmcd8qjy6y6xkghmaf6fu3ffga99a59up04lrjnhpl8afzj7w4yyxw
    value: 14

# The initial certificates.
initial_certs:
  - cert1qsqqqqqqqqqqqqqqqqqqqqqqqr2sr5860cvq6vuc05tlwl9lwrs5vw7wq8fjm9fw6mucy0cdd84n0c6ljv2p03s8tc8nukzcrx87zkp3hflm2ymglghs4sn60xgryu57pznzff92ldaymh34u36z6fvdqnzl8my8ucttn09sehq8pdgrle35k3spqpq2s44c5mudrr2c3d0pelf75tjk4ezmsqfxhvjlawxvmcnluc0tcl7kfh4hveatrfuu5fzg74hxpucf0sh6v4l7hhkpneaa02lmp6j8q5jqgzt4

# the initial deposits present in the blockchain but utilising the
# legacy cardano address format
legacy_funds:
  - address: 48mDfYyQn21iyEPzCfkATEHTwZBcZJqXhRJezmswfvc6Ne89u1axXsiazmgd7SwT8VbafbVnCvyXhBSMhSkPiCezMkqHC4dmxRahRC86SknFu6JF6hwSg8
    value: 123
```
