### ISSUE TITLE
Test fail: Cardano.Wallet.Primitive.Fee.prop_rebalanceSelection The fee balancing algorithm converges for any coin selection.

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#2183]
# Context
 
https://github.com/input-output-hk/cardano-wallet/pull/2168#issuecomment-698275912
https://hydra.iohk.io/build/4208599

# Test Case

```
Cardano.Wallet.Primitive.Fee.prop_rebalanceSelection
```

# Failure / Counter-example

```
Failures:

  test/unit/Cardano/Wallet/Primitive/FeeSpec.hs:379:9: 
  1) Cardano.Wallet.Primitive.Fee.prop_rebalanceSelection The fee balancing algorithm converges for any coin selection.
       Falsifiable (after 7960 tests):
         SaveMoney
         Coin {getCoin = 147770}
         selection (before):
         inputs: - 3rd 999038d5 (~ 199907 @ 61646472...64722d30)
         withdrawal: 777110
         reclaim: 637704
         outputs:
           - 113352 @ 61646472...64722d33
           - 187703 @ 61646472...64722d31
           - 84642 @ 61646472...64722d32
           - 192149 @ 61646472...64722d33
           - 48097 @ 61646472...64722d30
           - 30977 @ 61646472...64722d30
           - 35346 @ 61646472...64722d31
           - 47281 @ 61646472...64722d32
           - 110448 @ 61646472...64722d31
           - 119598 @ 61646472...64722d32
         change: [7424]
         deposit: 281458
         
         selection (after):
         inputs: - 3rd 999038d5 (~ 199907 @ 61646472...64722d30)
         withdrawal: 777110
         reclaim: 637704
         outputs:
           - 113352 @ 61646472...64722d33
           - 187703 @ 61646472...64722d31
           - 84642 @ 61646472...64722d32
           - 192149 @ 61646472...64722d33
           - 48097 @ 61646472...64722d30
           - 30977 @ 61646472...64722d30
           - 35346 @ 61646472...64722d31
           - 47281 @ 61646472...64722d32
           - 110448 @ 61646472...64722d31
           - 119598 @ 61646472...64722d32
         change: [147770]
         deposit: 281458
         
         delta (before): 356246
         delta (after):  215900
         total fee:      215900
         remaining fee:  0
         

  To rerun use: --match "/Cardano.Wallet.Primitive.Fee/prop_rebalanceSelection/The fee balancing algorithm converges for any coin selection./"
```

---

# Resolution 

---

# QA
