### ISSUE TITLE
Release artifact version string differs from what actual binary returns

### ISSUE THREAD

**Issue by den-is** [cardano-foundation/cardano-wallet#2690]
SysOps minor issue related to consistency and conventions.

I'm building small automation script to setup cardano-wallet component on a node - why not :)

So for example: Release tag in the git repo and github releases web UI says **v2021-05-26**
But actual binaries return
```
cardano-wallet version
2021.5.26 (git revision: 7426ccc17ecffcc112abf5e8382bcb89cb24f771)
```

Difference in `v`, `-`, `0`

while it is easy to manipulate outputs, like bellow, imho better consistency is always beneficial.
```yaml
# automation done using ansible
- name: Normalizing cardano release version part1
  set_fact:
    normalized_wallet_new_v_list: "{{ wallet_v.split('-') }}"

- name: Normalizing cardano release version part2
  set_fact:
    normalized_wallet_new_v: "{{ normalized_wallet_new_v_list[0] | replace('v', '') }}.{{ normalized_wallet_new_v_list[1] | replace('0', '') }}.{{ normalized_wallet_new_v_list[2] | replace('0', '') }}"

# actual binary version is caught like so and it is ok to skip right-most part of the output:
cardano-wallet version | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+"
```
Above is still error-prone because that snippet removes zero from such digits like 10, 20, 30 too. Of course, there are dozen bash methods to achieve the required result. - But hopefully, you got the idea, what it takes to compare not-consistent version strings. 

### Jira ticket

ADP-987
