### ISSUE TITLE
List stake distribution and stake pool statistics 

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#713]
# Context

:information_source: This ticket is now an aggregation of:

https://github.com/input-output-hk/cardano-wallet/issues/712
https://github.com/input-output-hk/cardano-wallet/issues/715
https://github.com/input-output-hk/cardano-wallet/issues/725
https://github.com/input-output-hk/cardano-wallet/issues/722

Jörmungandr provides an [endpoint](https://input-output-hk.github.io/jormungandr/jcli/rest.html#get-stake-distribution) for this with the following yaml-ified response format: 
```
epoch: 228      # Epoch of last block
stake:
  dangling: 0 # Total value stored in accounts, but assigned to nonexistent pools
  pools:
    - - 5cf03f333f37eb7b987dbc9017b8a928287a3d77d086cd93cd9ad05bcba7e60f # stake pool ID
      - 1000000000000                                                    # staked value
    - - 3815602c096fcbb91072f419c296c3dfe1f730e0f446a9bd2553145688e75615 # stake pool ID
      - 1000000000000                                                    # staked value
  unassigned: 0 # Total value stored in accounts, but not assigned to any pool
```

**Todo**: When run with BFT-config, jörmungandr only returns `{"epoch":2521}`. How do we handle that?

# Decision

- Extend `NetworkLayer` and `JörmungandrLayer` to allow fetching this endpoint.

It should have a return-type similar to
```haskell
(EpochNumber, [(PoolId, Stake)])
where
newtype Stake = Stake { getStakeLovelace :: Natural }
newtype PoolId = PoolVRFPubKey ByteString -- 32 bytes long

```

# Acceptance Criteria

1. Our Jörmungandr client _must_ be able to fetch stake pool distribution
1. We _must_ be able to retrieve stake of each pool and the epoch for which the results are valid
1. We _should_ be able to ignore dangling and unassigned stake
1. Users _must_ be able to list stake pools via the CLI
1. It _must_ be possible to eventually get an up-to-date distribution and statistics even with the events of rollbacks
1. It _must_ be possible to know how many blocks each stake pool in the current epoch has produced
1. Distribution and pool statistics _must_ be persisted so that it can be restored swiftly between restarts.
1.  Wallet API clients _must_ be able to list stake-pools and get their id, approximate performance and stake.
1.  If API results are unavailable, this _must_ be presented appropriately to the user.
1. The API response _should not_ be paginated
1.  Swagger.yaml _must_ be updated

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `master`  |

# QA 

- integration tests, checking that we can list stake-pools, some correctness of data, and for error message when results are unavailable https://github.com/input-output-hk/cardano-wallet/blob/8ba0c261e7ae3a687c218db457b4e079e63b8155/lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/StakePools.hs#L43-L82
- There exist properties for the Sqlite DB -> https://github.com/input-output-hk/cardano-wallet/blob/8ba0c261e7ae3a687c218db457b4e079e63b8155/lib/core/test/unit/Cardano/Pool/DB/Properties.hs#L95-L128
- Two interesting cases of `combineMetrics` is tested https://github.com/input-output-hk/cardano-wallet/blob/8ba0c261e7ae3a687c218db457b4e079e63b8155/lib/core/test/unit/Cardano/Pool/MetricsSpec.hs#L49-L72
- There might **not be** be race-conditions anymore https://github.com/input-output-hk/cardano-wallet/blob/8ba0c261e7ae3a687c218db457b4e079e63b8155/lib/core/src/Cardano/Pool/Metrics.hs#L170-L173
