### ISSUE TITLE
Implement 'joinStakePool' endpoint 

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#896]
# Context

#### Endpoint
```yaml
/stake-pools/{stakePoolId}/wallets/{walletId}:  
  put:  
    operationId: joinStakePool  
    parameters: 
      - *parametersStakePoolId  
      - *parametersWalletId 
      - <<: *parametersBody 
        schema: *parametersJoinStakePool
    responses: *responsesJoinStakePool
```
#### Input
```yaml
x-parametersJoinStakePool: &parametersJoinStakePool   
  properties: 
    passphrase:   
      <<: *walletPassphrase
      description: The wallet's master passphrase. 
```
#### Output
```yaml
x-responsesJoinStakePool: &responsesJoinStakePool 
  <<: *responsesErr400
  ...   
  202:
    description: Accepted 
    schema: *ApiTransaction  
```

### Request flow

A typical request flow goes as follows:

- Request is received, payload contains a PoolId
- Verify that the pool exists
- Create (and balance) a special transaction where flat certificate fees are taken into account
- Retrieve root private key for a wallet
- Derive a delegation account from the root key 
- Sign the special transaction with an extra payload: (account_key | pool_id)
- Submit the transaction 
- Return transaction as response

# Decision

- Implement 'Delegate' endpoint in the API
  - `deriveAddressPrivateKey` can be used to derive an reward account private key
    from an account private key (`AccountingStyle=MutableAccount` and index = `minBound`)

  - `mkCertificateTx` (from #893) can be used to correctly format a transaction

  - Construct an initial coin selection with no outputs and only one change and use 'adjustForFee' to balance the transaction. Making sure to use fee options adequately. There's currently an invariant in `adjustForFee` which requires outputs of a coin selection to be non-empty. This is wrong and should require instead that the union of change + outputs is non empty.

# Acceptance Criteria

1. Wallets _must_ only use accounting_style = 2  and account_index = 0 per `account'` for creating delegation accounts. Said differently, there _must_ be only one delegation account per wallet account. 
1. As an API user, I _must_ be able to delegate to a particular stake pool using its pool id.
1. Wallet _should_ check that the stake pool exists and fail accordingly if the user tries to join a stake pool that doesn't exists
1. The `delegation` field from the wallet metadata _should_ be ignored at the moment and nothing should be done regarding this.

---

# Development Plan

[x] Add implementation of joinStakePool on Api.Server level with errors 
[x] Add impl of signTx when mkDelegationCertTx is in master
[x] Consider reusing create/sign/submit parts between Tx and Cert
[x] review joinStakePoolEp in DSL
[x] make sure it works with discovery solution when corresponding PRs are merged 

# PR

| Number   | Base      |
| ---      | ---       |
| #970        | `master`  |
| #1019         | `master`  |
| #1061          | `master`  |
| #1068           | `master`  |
| #1084            | `master`  |

# QA
